"""
Similarity calculation services
"""
from typing import Literal
from langchain_core.pydantic_v1 import BaseModel, Field
from ollama import chat


class RelevanceResult(BaseModel):
    """Result model for relevance classification."""
    relevance: Literal[
        "Exact Match",
        "No Overlap",
        "Partial Overlap",
        "Subset",
        "Superset",
        "Upstream/Downstream Relation",
        "Conceptual Intersection",
        "Alternative Technology Context"
    ] = Field(
        ...,
        description="The relationship between the question and the given programming technique"
    )
    explanation: str = Field(
        ...,
        description="A brief explanation of the relationship"
    )


class AnswerSimilarityResult(BaseModel):
    """Result model for answer similarity classification."""
    similarity: Literal[
        "Exact Match",
        "High Similarity",
        "Partial Match",
        "Low Similarity",
        "No Match"
    ] = Field(
        ...,
        description="The similarity between the accepted answer and LLM solution"
    )
    explanation: str = Field(
        ...,
        description="A brief explanation of the similarity"
    )


class SimilarityService:
    """
    Service for calculating various types of similarity.
    """
    
    @staticmethod
    def classify_relevance(question: str, language: str) -> str:
        """
        Classify the relevance between a question and a programming technique.
        
        Args:
            question: User question
            language: Programming technique/language to compare against
            
        Returns:
            Relevance classification string
        """
        relationship_types = {
            "Exact Match": "The user's question fully aligns with the given technique.",
            "No Overlap": "The user's question is unrelated to the given technique.",
            "Partial Overlap": "The user's question partially involves the given technique.",
            "Subset": "The user's question is entirely within a smaller scope of the given technique.",
            "Superset": "The user's question covers multiple techniques, including the given one.",
            "Upstream/Downstream Relation": "The user's question uses a technology that builds on or underlies the given one.",
            "Conceptual Intersection": "The user's question touches on a broader concept that the given technique is part of.",
            "Alternative Technology Context": "The user's question uses a different language/tech that serves a similar purpose."
        }

        response = chat(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a smart assistant. Analyze the user's question and determine the relationship "
                        f"between the question's relevant programming techniques and the given programming technique: {language}.\n"
                        "You must respond in JSON format with two fields:\n"
                        "- 'relevance': one of the following labels:\n"
                        "  1. 'Exact Match'\n"
                        "  2. 'No Overlap'\n"
                        "  3. 'Partial Overlap'\n"
                        "  4. 'Subset'\n"
                        "  5. 'Superset'\n"
                        "  6. 'Upstream/Downstream Relation'\n"
                        "  7. 'Conceptual Intersection'\n"
                        "  8. 'Alternative Technology Context'\n"
                        "- 'explanation': a brief explanation of the relationship\n\n"
                        "Example response:\n"
                        "{\n"
                        "  'relevance': 'Exact Match',\n"
                        "  'explanation': 'The user's question fully aligns with the given technique.'\n"
                        "}"
                    )
                },
                {
                    "role": "user",
                    "content": question
                }
            ],
            model="llama3",
            format=RelevanceResult.schema(),
        )

        result = RelevanceResult.parse_raw(response['message']['content'])
        
        return f"{result.relevance} – {relationship_types[result.relevance]}"
    
    @staticmethod
    def calculate_answer_similarity(accepted_answer: str, llm_solution: str) -> str:
        """
        Calculate similarity between accepted answer and LLM solution.
        
        Args:
            accepted_answer: Accepted answer from Stack Overflow
            llm_solution: Solution generated by LLM
            
        Returns:
            Similarity classification string
        """
        similarity_types = {
            "Exact Match": "The LLM solution is almost identical to the accepted answer.",
            "High Similarity": "The LLM solution closely matches the key points of the accepted answer.",
            "Partial Match": "The LLM solution shares some common elements with the accepted answer.",
            "Low Similarity": "The LLM solution has minimal overlap with the accepted answer.",
            "No Match": "The LLM solution is completely different from the accepted answer."
        }

        response = chat(
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a smart assistant. Analyze the similarity between the accepted answer and LLM solution. "
                        "If accepted answer is empty, return 'No Match'.\n"
                        "You must respond in JSON format with two fields:\n"
                        "- 'similarity': one of the following labels:\n"
                        "  1. 'Exact Match'\n"
                        "  2. 'High Similarity'\n"
                        "  3. 'Partial Match'\n"
                        "  4. 'Low Similarity'\n"
                        "  5. 'No Match'\n"
                        "- 'explanation': a brief explanation of the similarity\n\n"
                        "Example response:\n"
                        "{\n"
                        "  'similarity': 'High Similarity',\n"
                        "  'explanation': 'The LLM solution closely matches the key points of the accepted answer.'\n"
                        "}"
                    )
                },
                {
                    "role": "user",
                    "content": f"Accepted Answer:\n{accepted_answer}\n\nLLM Solution:\n{llm_solution}"
                }
            ],
            model="llama3",
            format=AnswerSimilarityResult.schema(),
        )

        result = AnswerSimilarityResult.parse_raw(response['message']['content'])
        
        return f"{result.similarity} – {similarity_types[result.similarity]}"

